Repository incwell-technology/bootcampBackend, pull requests merged in 2019-05, with the labels that each got.

#5 Api
  .gitignore
  api/__init__.py
  api/admin.py
  api/apps.py
  api/models.py
  api/tests.py
  api/urls.py
  api/views.py
  bootcamp/admin.py
  bootcamp/api.py
  bootcamp/migrations/0001_initial.py
  bootcamp/migrations/__init__.py
  bootcamp/models.py
  bootcamp/serializers.py
  bootcampBackend/secrets.key
  bootcampBackend/settings.py
  bootcampBackend/urls.py
  requirements.txt
  syllabus/admin.py
  syllabus/api.py
  syllabus/migrations/0001_initial.py
  syllabus/migrations/__init__.py
  syllabus/models.py
  syllabus/serializers.py
  visitor/admin.py
  visitor/api.py
  visitor/migrations/0001_initial.py
  visitor/migrations/__init__.py
  visitor/models.py
  visitor/serializers.py
Labels: bug

#8 bug: merge conflict
  bootcampBackend/urls.py
Labels: bug

#10 bug: courses link fixed
  .gitignore
  bootcamp/migrations/0001_initial.py
  bootcamp/migrations/0002_auto_20190505_1915.py
  syllabus/migrations/0001_initial.py
  syllabus/models.py
  visitor/migrations/0001_initial.py
  visitor/migrations/0002_auto_20190505_1915.py
Labels: bug

#11 feat: google analytics added
  bootcamp/templates/bootcamp/base.html
Labels: enhancement

#12 feat: category added for mentors
  bootcamp/admin.py
  bootcamp/models.py
  bootcamp/templates/bootcamp/mentors.html
  bootcamp/views.py
Labels: enhancement

#13 feat: user can enroll and talk with mentors
  bootcamp/common/register_user.py
  bootcamp/migrations/0001_initial.py
  bootcamp/templates/bootcamp/base.html
  bootcamp/templates/bootcamp/enroll.html
  bootcamp/templates/bootcamp/notification.html
  bootcamp/templates/bootcamp/talk-to-mentors.html
  bootcamp/urls.py
  bootcamp/views.py
  syllabus/migrations/0001_initial.py
  visitor/admin.py
  visitor/api.py
  visitor/migrations/0001_initial.py
  visitor/models.py
  visitor/serializers.py
Labels: enhancement

#15 refactor: mentors frontend changed
  bootcamp/static/bootcamp/assets/bkg-mentors.png
  bootcamp/static/bootcamp/assets/mentors-trophy.png
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/templates/bootcamp/base.html
  bootcamp/templates/bootcamp/layout.html
  bootcamp/templates/bootcamp/mentors.html
  bootcamp/views.py
Labels: refactor

#16 Enroll frontend
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/templates/bootcamp/base.html
  bootcamp/templates/bootcamp/mentors.html
Labels: refactor

#17 Prepare for the release v0.2.0
  .gitignore
  bootcamp/admin.py
  bootcamp/common/register_user.py
  bootcamp/migrations/0001_initial.py
  bootcamp/migrations/0002_auto_20190505_1915.py
  bootcamp/models.py
  bootcamp/static/bootcamp/assets/Path_244.svg
  bootcamp/static/bootcamp/assets/bkg-mentors.png
  bootcamp/static/bootcamp/assets/logo.ico
  bootcamp/static/bootcamp/assets/mentors-trophy.png
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/static/bootcamp/assets/undraw_moving.svg
  bootcamp/static/bootcamp/assets/wow/animate.css
  bootcamp/static/bootcamp/assets/wow/animate.js
  bootcamp/templates/bootcamp/base.html
  bootcamp/templates/bootcamp/enroll.html
  bootcamp/templates/bootcamp/index.html
  bootcamp/templates/bootcamp/layout.html
  bootcamp/templates/bootcamp/mentors.html
  bootcamp/templates/bootcamp/notification.html
  bootcamp/templates/bootcamp/talk-to-mentors.html
  bootcamp/urls.py
  bootcamp/views.py
  bootcampBackend/settings.py
  syllabus/migrations/0001_initial.py
  syllabus/models.py
  visitor/admin.py
  visitor/api.py
  visitor/migrations/0001_initial.py
  visitor/migrations/0002_auto_20190505_1915.py
  visitor/models.py
  visitor/serializers.py
Labels: feature

#18 bug:merge conflict solved
  bootcamp/templates/bootcamp/mentors.html
Labels: bug

#22 design: active navbar and image changed
  bootcamp/static/bootcamp/assets/mentors-handshake.png
  bootcamp/static/bootcamp/assets/mentors-monitor.png
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/templates/bootcamp/base.html
  bootcamp/templates/bootcamp/mentors.html
Labels: refactor

#24 feat: about us content from database
  bootcamp/templates/bootcamp/about.html
  bootcamp/views.py
Labels: feature

#25 feat: contact us page integrated
  bootcamp/common/register_user.py
  bootcamp/static/bootcamp/assets/CHARCTER.svg
  bootcamp/static/bootcamp/assets/char.svg
  bootcamp/static/bootcamp/assets/newcorner.svg
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/static/bootcamp/assets/undraw_working_remotely_jh40.svg
  bootcamp/templates/bootcamp/about.html
  bootcamp/templates/bootcamp/base.html
  bootcamp/templates/bootcamp/contact.html
  bootcamp/templates/bootcamp/courses.html
  bootcamp/templates/bootcamp/error.html
  bootcamp/urls.py
  bootcamp/views.py
  visitor/admin.py
  visitor/models.py
Labels: enhancement

#26 feat: mentors background dynamic
  bootcamp/static/bootcamp/assets/MentorsBannerSite.png
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/templates/bootcamp/mentors.html
  bootcamp/views.py
Labels: enhancement

#28 feat: scholarship added and courses redesign
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/templates/bootcamp/base.html
  bootcamp/templates/bootcamp/courses.html
  bootcamp/urls.py
  bootcamp/views.py
  visitor/admin.py
  visitor/models.py
Labels: enhancement

#29 bug: courses css
  bootcamp/static/bootcamp/assets/style.css
Labels: bug

#30 Dev
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/templates/bootcamp/base.html
  bootcamp/templates/bootcamp/courses.html
  bootcamp/urls.py
  bootcamp/views.py
  visitor/admin.py
  visitor/models.py
Labels: enhancement

#31 refac: mentors page editted
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/templates/bootcamp/mentors.html
Labels: refactor

#32 feat: scholarship page integrated
  bootcamp/static/bootcamp/assets/assignment.png
  bootcamp/static/bootcamp/assets/materialize.css
  bootcamp/static/bootcamp/assets/materialize.js
  bootcamp/static/bootcamp/assets/meeting.png
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/templates/bootcamp/base.html
  bootcamp/templates/bootcamp/enroll.html
  bootcamp/templates/bootcamp/scholarship.html
  bootcamp/urls.py
  bootcamp/views.py
Labels: enhancement, feature

#33 bug: about us problem fixed
  bootcamp/static/bootcamp/assets/style.css
  bootcamp/templates/bootcamp/about.html
  bootcamp/templates/bootcamp/base.html
  bootcamp/templates/bootcamp/courses.html
  bootcamp/views.py
Labels: bug

#37 bug: added 404 page, refactor about page
  bootcamp/static/bootcamp/assets/Shortlist.png
  bootcamp/templates/404.html
  bootcamp/templates/bootcamp/about.html
  bootcamp/templates/bootcamp/scholarship.html
  bootcampBackend/settings.py
Labels: bug

#38 refactor: about us image changed
  bootcamp/static/bootcamp/assets/behindthescene.jpg
  bootcamp/static/bootcamp/assets/behindthescene1.jpg
  bootcamp/static/bootcamp/assets/behindthescene2.jpg
  bootcamp/static/bootcamp/assets/behindthescene3.jpeg
  bootcamp/templates/bootcamp/about.html
Labels: refactor
